// Generated by CoffeeScript 1.7.1
(function() {
  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/main', {
        templateUrl: 'templates/main.html',
        controller: 'mainCtrl'
      }).otherwise({
        redirectTo: '/main'
      });
    }
  ]);

}).call(this);
